import "@/styles/globals.css";
import type { Metadata } from "next";
import { ReactNode } from "react";
import { AuthProvider } from "./providers";
import { Toaster } from "sonner";
import { Poppins } from "next/font/google";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "E-Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={poppins.variable}>
      <head>
        <title>My E-commerce</title>
      </head>
      <body>
        <AuthProvider>
          <Toaster position="top-right" />
          <Header />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
