-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgiG8GBH7vtyeCn4tv
aSACd+fcDMJF8QpdlXXrCi7zCSWgCgYIKoZIzj0DAQehRANCAATth9+WAg+Q/NFh
7dLdB1oyzRvwbRt4GZZYNjaTxpRxYoDzBw5WlYEA/JpWiS2xmla1XGwo+JaW7/QM
6vxisnkt
-----END PRIVATE KEY-----